CREATE TABLE teams (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    sensei_id INTEGER NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (sensei_id) REFERENCES characters(id) ON DELETE RESTRICT
);
ALTER TABLE characters ADD COLUMN team_id INTEGER REFERENCES teams(id) ON DELETE SET NULL;