ALTER TABLE characters ADD COLUMN team_id INTEGER REFERENCES teams(id) ON DELETE SET NULL;
ALTER TABLE teams ADD COLUMN sensei_id INTEGER REFERENCES characters(id) ON DELETE RESTRICT;

DROP TABLE team_members;