package seed

import (
	"database/sql"
	"time"

	"github.com/biplob-codes/mockly/internal/database/sqlc"
)

var CharacterData = []sqlc.Character{
	{
		ID:        1,
		Name:      "Naruto Uzumaki",
		Nickname:  sql.NullString{String: "Seventh Hokage", Valid: true},
		Clan:      sql.NullString{String: "Uzumaki", Valid: true},
		Age:       sql.NullInt64{Int64: 17, Valid: true},
		Rank:      "Kage",
		Birthdate: time.Date(1997, 10, 10, 0, 0, 0, 0, time.UTC),
		VillageID: 1,
		TeamID:    sql.NullInt64{Valid: false},
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
	{
		ID:        2,
		Name:      "Sasuke Uchiha",
		Nickname:  sql.NullString{String: "Last Uchiha", Valid: true},
		Clan:      sql.NullString{String: "Uchiha", Valid: true},
		Age:       sql.NullInt64{Int64: 17, Valid: true},
		Rank:      "Jonin",
		Birthdate: time.Date(1997, 7, 23, 0, 0, 0, 0, time.UTC),
		VillageID: 1,
		TeamID:    sql.NullInt64{Valid: false},
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
	{
		ID:        3,
		Name:      "Sakura Haruno",
		Nickname:  sql.NullString{String: "Cherry Blossom", Valid: true},
		Clan:      sql.NullString{Valid: false},
		Age:       sql.NullInt64{Int64: 17, Valid: true},
		Rank:      "Jonin",
		Birthdate: time.Date(1997, 3, 28, 0, 0, 0, 0, time.UTC),
		VillageID: 1,
		TeamID:    sql.NullInt64{Valid: false},
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
	{
		ID:        4,
		Name:      "Kakashi Hatake",
		Nickname:  sql.NullString{String: "Copy Ninja", Valid: true},
		Clan:      sql.NullString{String: "Hatake", Valid: true},
		Age:       sql.NullInt64{Int64: 31, Valid: true},
		Rank:      "Kage",
		Birthdate: time.Date(1990, 9, 15, 0, 0, 0, 0, time.UTC),
		VillageID: 1,
		TeamID:    sql.NullInt64{Valid: false},
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
	{
		ID:        5,
		Name:      "Might Guy",
		Nickname:  sql.NullString{String: "Handsome Beast", Valid: true},
		Clan:      sql.NullString{Valid: false},
		Age:       sql.NullInt64{Int64: 32, Valid: true},
		Rank:      "Jonin",
		Birthdate: time.Date(1990, 1, 1, 0, 0, 0, 0, time.UTC),
		VillageID: 1,
		TeamID:    sql.NullInt64{Valid: false},
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
	{
		ID:        6,
		Name:      "Shikamaru Nara",
		Nickname:  sql.NullString{String: "Shadow User", Valid: true},
		Clan:      sql.NullString{String: "Nara", Valid: true},
		Age:       sql.NullInt64{Int64: 17, Valid: true},
		Rank:      "Jonin",
		Birthdate: time.Date(1997, 9, 22, 0, 0, 0, 0, time.UTC),
		VillageID: 1,
		TeamID:    sql.NullInt64{Valid: false},
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
	{
		ID:        7,
		Name:      "Hinata Hyuga",
		Nickname:  sql.NullString{Valid: false},
		Clan:      sql.NullString{String: "Hyuga", Valid: true},
		Age:       sql.NullInt64{Int64: 17, Valid: true},
		Rank:      "Chunin",
		Birthdate: time.Date(1997, 12, 27, 0, 0, 0, 0, time.UTC),
		VillageID: 1,
		TeamID:    sql.NullInt64{Valid: false},
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
	{
		ID:        8,
		Name:      "Jiraiya",
		Nickname:  sql.NullString{String: "Toad Sage", Valid: true},
		Clan:      sql.NullString{Valid: false},
		Age:       sql.NullInt64{Int64: 54, Valid: true},
		Rank:      "Sannin",
		Birthdate: time.Date(1954, 11, 11, 0, 0, 0, 0, time.UTC),
		VillageID: 1,
		TeamID:    sql.NullInt64{Valid: false},
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
	{
		ID:        9,
		Name:      "Tsunade",
		Nickname:  sql.NullString{String: "Fifth Hokage", Valid: true},
		Clan:      sql.NullString{String: "Senju", Valid: true},
		Age:       sql.NullInt64{Int64: 51, Valid: true},
		Rank:      "Kage",
		Birthdate: time.Date(1957, 8, 2, 0, 0, 0, 0, time.UTC),
		VillageID: 1,
		TeamID:    sql.NullInt64{Valid: false},
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
	{
		ID:        10,
		Name:      "Minato Namikaze",
		Nickname:  sql.NullString{String: "Yellow Flash", Valid: true},
		Clan:      sql.NullString{Valid: false},
		Age:       sql.NullInt64{Int64: 24, Valid: true},
		Rank:      "Kage",
		Birthdate: time.Date(1979, 1, 25, 0, 0, 0, 0, time.UTC),
		VillageID: 1,
		TeamID:    sql.NullInt64{Valid: false},
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
	{
		ID:        11,
		Name:      "Hiruzen Sarutobi",
		Nickname:  sql.NullString{String: "Professor", Valid: true},
		Clan:      sql.NullString{String: "Sarutobi", Valid: true},
		Age:       sql.NullInt64{Int64: 68, Valid: true},
		Rank:      "Kage",
		Birthdate: time.Date(1929, 4, 8, 0, 0, 0, 0, time.UTC),
		VillageID: 1,
		TeamID:    sql.NullInt64{Valid: false},
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
	{
		ID:        12,
		Name:      "Itachi Uchiha",
		Nickname:  sql.NullString{String: "Crow", Valid: true},
		Clan:      sql.NullString{String: "Uchiha", Valid: true},
		Age:       sql.NullInt64{Int64: 21, Valid: true},
		Rank:      "Jonin",
		Birthdate: time.Date(1988, 6, 9, 0, 0, 0, 0, time.UTC),
		VillageID: 1,
		TeamID:    sql.NullInt64{Valid: false},
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
	{
		ID:        13,
		Name:      "Yamato",
		Nickname:  sql.NullString{String: "Wood Style User", Valid: true},
		Clan:      sql.NullString{Valid: false},
		Age:       sql.NullInt64{Int64: 26, Valid: true},
		Rank:      "Jonin",
		Birthdate: time.Date(1972, 8, 10, 0, 0, 0, 0, time.UTC),
		VillageID: 1,
		TeamID:    sql.NullInt64{Valid: false},
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
	{
		ID:        14,
		Name:      "Orochimaru",
		Nickname:  sql.NullString{String: "Snake Sannin", Valid: true},
		Clan:      sql.NullString{Valid: false},
		Age:       sql.NullInt64{Int64: 54, Valid: true},
		Rank:      "Sannin",
		Birthdate: time.Date(1954, 10, 27, 0, 0, 0, 0, time.UTC),
		VillageID: 1,
		TeamID:    sql.NullInt64{Valid: false},
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
	{
		ID:        15,
		Name:      "Obito Uchiha",
		Nickname:  sql.NullString{String: "Tobi", Valid: true},
		Clan:      sql.NullString{String: "Uchiha", Valid: true},
		Age:       sql.NullInt64{Int64: 31, Valid: true},
		Rank:      "Jonin",
		Birthdate: time.Date(1970, 2, 10, 0, 0, 0, 0, time.UTC),
		VillageID: 1,
		TeamID:    sql.NullInt64{Valid: false},
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
	{
		ID:        16,
		Name:      "Madara Uchiha",
		Nickname:  sql.NullString{String: "Ghost of the Uchiha", Valid: true},
		Clan:      sql.NullString{String: "Uchiha", Valid: true},
		Age:       sql.NullInt64{Int64: 80, Valid: true},
		Rank:      "Jonin",
		Birthdate: time.Date(1, 12, 24, 0, 0, 0, 0, time.UTC),
		VillageID: 1,
		TeamID:    sql.NullInt64{Valid: false},
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
	{
		ID:        17,
		Name:      "Hashirama Senju",
		Nickname:  sql.NullString{String: "God of Shinobi", Valid: true},
		Clan:      sql.NullString{String: "Senju", Valid: true},
		Age:       sql.NullInt64{Int64: 60, Valid: true},
		Rank:      "Kage",
		Birthdate: time.Date(1, 10, 23, 0, 0, 0, 0, time.UTC),
		VillageID: 1,
		TeamID:    sql.NullInt64{Valid: false},
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
	{
		ID:        18,
		Name:      "Tobirama Senju",
		Nickname:  sql.NullString{String: "Second Hokage", Valid: true},
		Clan:      sql.NullString{String: "Senju", Valid: true},
		Age:       sql.NullInt64{Int64: 55, Valid: true},
		Rank:      "Kage",
		Birthdate: time.Date(1, 2, 19, 0, 0, 0, 0, time.UTC),
		VillageID: 1,
		TeamID:    sql.NullInt64{Valid: false},
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
	{
		ID:        19,
		Name:      "Gaara",
		Nickname:  sql.NullString{String: "Kazekage of the Sand", Valid: true},
		Clan:      sql.NullString{Valid: false},
		Age:       sql.NullInt64{Int64: 15, Valid: true},
		Rank:      "Kage",
		Birthdate: time.Date(1999, 1, 19, 0, 0, 0, 0, time.UTC),
		VillageID: 2,
		TeamID:    sql.NullInt64{Valid: false},
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
	{
		ID:        20,
		Name:      "Sasori",
		Nickname:  sql.NullString{String: "Red Sand Scorpion", Valid: true},
		Clan:      sql.NullString{Valid: false},
		Age:       sql.NullInt64{Int64: 35, Valid: true},
		Rank:      "Jonin",
		Birthdate: time.Date(1980, 9, 8, 0, 0, 0, 0, time.UTC),
		VillageID: 2,
		TeamID:    sql.NullInt64{Valid: false},
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
	{
		ID:        21,
		Name:      "Zabuza Momochi",
		Nickname:  sql.NullString{String: "Demon of the Hidden Mist", Valid: true},
		Clan:      sql.NullString{Valid: false},
		Age:       sql.NullInt64{Int64: 26, Valid: true},
		Rank:      "Jonin",
		Birthdate: time.Date(1970, 11, 18, 0, 0, 0, 0, time.UTC),
		VillageID: 3,
		TeamID:    sql.NullInt64{Valid: false},
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
	{
		ID:        22,
		Name:      "Kisame Hoshigaki",
		Nickname:  sql.NullString{String: "Tailless Tailed Beast", Valid: true},
		Clan:      sql.NullString{Valid: false},
		Age:       sql.NullInt64{Int64: 32, Valid: true},
		Rank:      "Jonin",
		Birthdate: time.Date(1970, 2, 18, 0, 0, 0, 0, time.UTC),
		VillageID: 3,
		TeamID:    sql.NullInt64{Valid: false},
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
	{
		ID:        23,
		Name:      "Onoki",
		Nickname:  sql.NullString{String: "Fence Sitter", Valid: true},
		Clan:      sql.NullString{Valid: false},
		Age:       sql.NullInt64{Int64: 82, Valid: true},
		Rank:      "Kage",
		Birthdate: time.Date(1, 2, 1, 0, 0, 0, 0, time.UTC),
		VillageID: 4,
		TeamID:    sql.NullInt64{Valid: false},
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
	{
		ID:        24,
		Name:      "Killer Bee",
		Nickname:  sql.NullString{String: "Eight-Tails Jinchuriki", Valid: true},
		Clan:      sql.NullString{Valid: false},
		Age:       sql.NullInt64{Int64: 33, Valid: true},
		Rank:      "Jonin",
		Birthdate: time.Date(1970, 7, 2, 0, 0, 0, 0, time.UTC),
		VillageID: 5,
		TeamID:    sql.NullInt64{Valid: false},
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
	{
		ID:        25,
		Name:      "A",
		Nickname:  sql.NullString{String: "Fourth Raikage", Valid: true},
		Clan:      sql.NullString{Valid: false},
		Age:       sql.NullInt64{Int64: 40, Valid: true},
		Rank:      "Kage",
		Birthdate: time.Date(1, 12, 30, 0, 0, 0, 0, time.UTC),
		VillageID: 5,
		TeamID:    sql.NullInt64{Valid: false},
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
	{
		ID:        26,
		Name:      "Nagato",
		Nickname:  sql.NullString{String: "Pain", Valid: true},
		Clan:      sql.NullString{String: "Uzumaki", Valid: true},
		Age:       sql.NullInt64{Int64: 35, Valid: true},
		Rank:      "Kage",
		Birthdate: time.Date(1985, 9, 19, 0, 0, 0, 0, time.UTC),
		VillageID: 6,
		TeamID:    sql.NullInt64{Valid: false},
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
	{
		ID:        27,
		Name:      "Konan",
		Nickname:  sql.NullString{String: "Angel", Valid: true},
		Clan:      sql.NullString{Valid: false},
		Age:       sql.NullInt64{Int64: 35, Valid: true},
		Rank:      "Jonin",
		Birthdate: time.Date(1985, 8, 24, 0, 0, 0, 0, time.UTC),
		VillageID: 6,
		TeamID:    sql.NullInt64{Valid: false},
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
}
