package seed

import (
	"database/sql"
	"time"

	"github.com/biplob-codes/mockly/internal/database/sqlc"
)

var JutsuData = []sqlc.Jutsu{
	// --- Academy / basic jutsu (E, D rank coverage) ---
	{ID: 1, Name: "Transformation Jutsu", Description: sql.NullString{String: "A basic academy technique that lets the user change their appearance into another person, object, or creature.", Valid: true}, Type: "Ninjutsu", Rank: "E", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 2, Name: "Clone Jutsu", Description: sql.NullString{String: "Creates illusory, intangible copies of the user for basic deception, one of the three core academy jutsu.", Valid: true}, Type: "Ninjutsu", Rank: "E", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 3, Name: "Substitution Jutsu", Description: sql.NullString{String: "Swaps the user's body with a nearby object at the last moment to escape an attack, a staple defensive reflex for every shinobi.", Valid: true}, Type: "Ninjutsu", Rank: "D", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 4, Name: "Rope Escape Technique", Description: sql.NullString{String: "A simple technique used to slip out of ropes or bindings by loosening the body's muscles and joints.", Valid: true}, Type: "Ninjutsu", Rank: "D", CreatedAt: time.Now(), UpdatedAt: time.Now()},

	// --- Ninjutsu ---
	{ID: 5, Name: "Shadow Clone Jutsu", Description: sql.NullString{String: "Creates solid, fully functional clones capable of independent combat, famously overused by Naruto to overwhelm opponents.", Valid: true}, Type: "Ninjutsu", Rank: "B", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 6, Name: "Multi Shadow Clone Jutsu", Description: sql.NullString{String: "An advanced variation that produces dozens or even hundreds of shadow clones simultaneously, taxing even skilled chakra users.", Valid: true}, Type: "Ninjutsu", Rank: "A", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 7, Name: "Rasengan", Description: sql.NullString{String: "A swirling sphere of concentrated chakra formed in the palm, delivering devastating close-range damage without hand seals.", Valid: true}, Type: "Ninjutsu", Rank: "A", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 8, Name: "Sage Art: Rasenshuriken", Description: sql.NullString{String: "A shuriken-shaped evolution of the Rasengan infused with wind-natured senjutsu chakra, capable of shredding an opponent at the cellular level.", Valid: true}, Type: "Ninjutsu", Rank: "S", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 9, Name: "Fire Style: Fireball Jutsu", Description: sql.NullString{String: "The signature Uchiha clan technique that expels a massive burst of flame from the user's mouth after a set of hand seals.", Valid: true}, Type: "Ninjutsu", Rank: "B", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 10, Name: "Fire Style: Phoenix Sage Fire Technique", Description: sql.NullString{String: "Launches a rapid barrage of small fireballs from the mouth, useful for both offense and misdirection in quick succession.", Valid: true}, Type: "Ninjutsu", Rank: "B", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 11, Name: "Chidori", Description: sql.NullString{String: "A concentrated blade of lightning chakra gathered in the hand, named for the chirping sound it produces, requiring immense speed to land safely.", Valid: true}, Type: "Ninjutsu", Rank: "A", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 12, Name: "Chidori Stream", Description: sql.NullString{String: "An advanced form of Chidori that spreads lightning chakra across the user's entire body, allowing wide-area offense and defense at once.", Valid: true}, Type: "Ninjutsu", Rank: "A", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 13, Name: "Kirin", Description: sql.NullString{String: "A forbidden lightning technique that draws down a natural thunderstorm and channels it into a strike of near-unblockable destructive force.", Valid: true}, Type: "Ninjutsu", Rank: "S", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 14, Name: "Water Style: Water Dragon Jutsu", Description: sql.NullString{String: "Forms a massive serpentine dragon out of surrounding water to crash into and overwhelm an opponent.", Valid: true}, Type: "Ninjutsu", Rank: "A", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 15, Name: "Water Style: Exploding Water Shockwave", Description: sql.NullString{String: "Releases an enormous surge of pressurized water capable of flooding and battering a wide area in an instant.", Valid: true}, Type: "Ninjutsu", Rank: "A", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 16, Name: "Water Style: Water Prison Jutsu", Description: sql.NullString{String: "Traps a target inside an inescapable orb of water, though it requires the caster's hand to maintain and control it.", Valid: true}, Type: "Ninjutsu", Rank: "B", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 17, Name: "Water Style: Water Shark Bomb", Description: sql.NullString{String: "Shapes gathered water into one or more shark-like projectiles that surge toward the target with crushing force.", Valid: true}, Type: "Ninjutsu", Rank: "B", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 18, Name: "Wood Style: Wood Dragon Jutsu", Description: sql.NullString{String: "Summons enormous wooden dragons from the ground to restrain or crush opponents, unique to those with Wood Style bloodline chakra.", Valid: true}, Type: "Ninjutsu", Rank: "S", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 19, Name: "Wood Style: Deep Forest Emergence", Description: sql.NullString{String: "Instantly transforms the surrounding terrain into a dense forest of towering trees, capable of reshaping an entire battlefield.", Valid: true}, Type: "Ninjutsu", Rank: "S", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 20, Name: "Shadow Possession Jutsu", Description: sql.NullString{String: "Extends the user's shadow to bind a target's own shadow, forcing them to mirror the caster's movements.", Valid: true}, Type: "Ninjutsu", Rank: "C", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 21, Name: "Shadow Neck Bind Jutsu", Description: sql.NullString{String: "A refined extension of shadow possession that lets the user's shadow choke a captured target directly.", Valid: true}, Type: "Ninjutsu", Rank: "C", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 22, Name: "Sand Coffin", Description: sql.NullString{String: "Encases a target completely in compressed sand, immobilizing them before a follow-up crushing technique.", Valid: true}, Type: "Ninjutsu", Rank: "A", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 23, Name: "Sand Tsunami", Description: sql.NullString{String: "Unleashes an overwhelming wave of sand capable of burying and devastating everything across a massive area.", Valid: true}, Type: "Ninjutsu", Rank: "S", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 24, Name: "Sand Shield", Description: sql.NullString{String: "An automatic defense of sand that reacts to protect the user from incoming attacks, even without conscious effort.", Valid: true}, Type: "Ninjutsu", Rank: "B", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 25, Name: "Puppet Technique: Ten Puppets Performance", Description: sql.NullString{String: "Simultaneously controls ten armed puppets with precise chakra strings, overwhelming opponents with coordinated strikes.", Valid: true}, Type: "Ninjutsu", Rank: "A", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 26, Name: "Puppet Technique: Poison Mist", Description: sql.NullString{String: "Releases a cloud of lethal poison gas from a hidden puppet mechanism to incapacitate anyone caught nearby.", Valid: true}, Type: "Ninjutsu", Rank: "B", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 27, Name: "Summoning Jutsu", Description: sql.NullString{String: "Calls forth a contracted creature to the battlefield using a blood signature and hand seals, ranging from small animals to massive bosses.", Valid: true}, Type: "Ninjutsu", Rank: "B", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 28, Name: "Summoning: Slug Divided Technique", Description: sql.NullString{String: "Splits the user's summoned slug into many smaller bodies to scout, heal allies, or coordinate across a wide area at once.", Valid: true}, Type: "Ninjutsu", Rank: "B", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 29, Name: "Edo Tensei", Description: sql.NullString{String: "A forbidden reanimation technique that resurrects the dead as near-immortal soldiers bound to the caster's will.", Valid: true}, Type: "Ninjutsu", Rank: "S", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 30, Name: "Body Flicker Jutsu", Description: sql.NullString{String: "A basic movement technique that lets the user travel short distances at high speed, appearing to vanish and reappear elsewhere.", Valid: true}, Type: "Ninjutsu", Rank: "C", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 31, Name: "Flying Thunder God Jutsu", Description: sql.NullString{String: "Allows instantaneous teleportation to any location marked with the technique's special seal, making the user nearly impossible to pin down.", Valid: true}, Type: "Ninjutsu", Rank: "S", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 32, Name: "Tailed Beast Ball", Description: sql.NullString{String: "A sphere of condensed tailed beast chakra launched at the target, capable of leveling mountains on impact.", Valid: true}, Type: "Ninjutsu", Rank: "S", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 33, Name: "Lava Style: Quicklime Congealing Jutsu", Description: sql.NullString{String: "Mixes earth and fire chakra to spew corrosive molten rock that hardens over anything it touches.", Valid: true}, Type: "Ninjutsu", Rank: "A", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 34, Name: "Particle Style: Atomic Dismantling Jutsu", Description: sql.NullString{String: "A rare kekkei tota technique that breaks matter down to the atomic level, disintegrating anything it comes into contact with.", Valid: true}, Type: "Ninjutsu", Rank: "S", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 35, Name: "Lightning Style: Lariat", Description: sql.NullString{String: "Envelops the arms in searing lightning chakra and delivers a devastating double-armed clothesline strike at high speed.", Valid: true}, Type: "Ninjutsu", Rank: "A", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 36, Name: "Shinra Tensei", Description: sql.NullString{String: "A Rinnegan technique that repels everything in the surrounding area with a single burst of invisible gravitational force.", Valid: true}, Type: "Ninjutsu", Rank: "S", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 37, Name: "Chibaku Tensei", Description: sql.NullString{String: "Draws in massive amounts of surrounding matter to form an artificial moon, capable of sealing away an entire tailed beast.", Valid: true}, Type: "Ninjutsu", Rank: "S", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 38, Name: "Paper Clone Jutsu", Description: sql.NullString{String: "Creates a body double made entirely of paper, letting the user observe or fight from a safe distance.", Valid: true}, Type: "Ninjutsu", Rank: "B", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 39, Name: "Paper Shuriken Jutsu", Description: sql.NullString{String: "Transforms the user's body or surroundings into countless razor-edged paper shuriken for a sudden coordinated strike.", Valid: true}, Type: "Ninjutsu", Rank: "C", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 40, Name: "Creation Rebirth", Description: sql.NullString{String: "A medical technique that stores excess chakra in a seal on the forehead, releasing it to heal fatal wounds instantly.", Valid: true}, Type: "Ninjutsu", Rank: "A", CreatedAt: time.Now(), UpdatedAt: time.Now()},

	// --- Taijutsu ---
	{ID: 41, Name: "Leaf Hurricane", Description: sql.NullString{String: "A spinning low kick that sweeps into a rising heel strike, a foundational taijutsu combo taught in the Hidden Leaf.", Valid: true}, Type: "Taijutsu", Rank: "C", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 42, Name: "Leaf Whirlwind", Description: sql.NullString{String: "A follow-up spinning kick technique that builds on the Leaf Hurricane for a stronger, more disorienting strike.", Valid: true}, Type: "Taijutsu", Rank: "C", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 43, Name: "Eight Gates Release", Description: sql.NullString{String: "Unlocks the body's internal chakra gates one by one, granting explosive strength and speed at severe cost to the user's body.", Valid: true}, Type: "Taijutsu", Rank: "S", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 44, Name: "Strong Fist", Description: sql.NullString{String: "A hard-hitting taijutsu style built around powerful, chakra-enhanced strikes meant to end fights in as few blows as possible.", Valid: true}, Type: "Taijutsu", Rank: "B", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 45, Name: "Gentle Fist", Description: sql.NullString{String: "A Hyuga clan taijutsu style that uses precise chakra strikes to damage an opponent's internal organs and chakra network directly.", Valid: true}, Type: "Taijutsu", Rank: "B", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 46, Name: "Eight Trigrams Sixty-Four Palms", Description: sql.NullString{String: "A rapid sequence of Gentle Fist strikes that seals dozens of an opponent's chakra points in a single relentless combo.", Valid: true}, Type: "Taijutsu", Rank: "A", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 47, Name: "Front Lotus", Description: sql.NullString{String: "A high-speed taijutsu technique that slams the target into the ground with tremendous force after a sudden aerial grapple.", Valid: true}, Type: "Taijutsu", Rank: "A", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 48, Name: "Afternoon Tiger", Description: sql.NullString{String: "A devastating point-blank strike delivered while the Eighth Gate is open, channeling near-fatal levels of chakra into a single blow.", Valid: true}, Type: "Taijutsu", Rank: "S", CreatedAt: time.Now(), UpdatedAt: time.Now()},

	// --- Genjutsu ---
	{ID: 49, Name: "Tsukuyomi", Description: sql.NullString{String: "A Mangekyo Sharingan genjutsu that traps the victim in an inescapable mental world where the caster controls time and space.", Valid: true}, Type: "Genjutsu", Rank: "S", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 50, Name: "Izanami", Description: sql.NullString{String: "A powerful genjutsu that locks a target into repeating the same events until they accept a change in their actions.", Valid: true}, Type: "Genjutsu", Rank: "S", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 51, Name: "Demonic Illusion: Mirror Heaven and Earth Change", Description: sql.NullString{String: "Alters the victim's perception of the entire surrounding landscape, disorienting them within a convincingly false world.", Valid: true}, Type: "Genjutsu", Rank: "A", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 52, Name: "Temple of Nirvana Genjutsu", Description: sql.NullString{String: "Releases spores that trigger a wide-area genjutsu, putting large numbers of people to sleep simultaneously.", Valid: true}, Type: "Genjutsu", Rank: "B", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 53, Name: "Crow Genjutsu", Description: sql.NullString{String: "Traps a target's vision in an illusion filled with swarming crows, breaking their focus before a follow-up attack.", Valid: true}, Type: "Genjutsu", Rank: "B", CreatedAt: time.Now(), UpdatedAt: time.Now()},

	// --- Kekkei Genkai ---
	{ID: 54, Name: "Sharingan", Description: sql.NullString{String: "The Uchiha clan's signature dojutsu, granting heightened perception, the ability to copy jutsu, and resistance to genjutsu.", Valid: true}, Type: "Kekkei Genkai", Rank: "A", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 55, Name: "Mangekyo Sharingan", Description: sql.NullString{String: "An evolved form of the Sharingan unlocked through great emotional trauma, granting access to unique and devastating abilities.", Valid: true}, Type: "Kekkei Genkai", Rank: "S", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 56, Name: "Byakugan", Description: sql.NullString{String: "The Hyuga clan's dojutsu, providing near-360-degree vision and the ability to see chakra points and pathways through solid objects.", Valid: true}, Type: "Kekkei Genkai", Rank: "A", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 57, Name: "Wood Style Bloodline", Description: sql.NullString{String: "A rare kekkei genkai combining earth and water chakra to create and control living wood, unique to the Senju clan's founder.", Valid: true}, Type: "Kekkei Genkai", Rank: "S", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 58, Name: "Susanoo", Description: sql.NullString{String: "A gigantic, humanoid avatar of chakra summoned through the Mangekyo Sharingan that shields and fights on the user's behalf.", Valid: true}, Type: "Kekkei Genkai", Rank: "S", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 59, Name: "Amaterasu", Description: sql.NullString{String: "Black flames summoned through the Mangekyo Sharingan that burn anything caught in the user's field of vision and never extinguish naturally.", Valid: true}, Type: "Kekkei Genkai", Rank: "S", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 60, Name: "Rinnegan", Description: sql.NullString{String: "A legendary dojutsu said to belong to the Sage of Six Paths, granting mastery over all six chakra natures and the Six Paths techniques.", Valid: true}, Type: "Kekkei Genkai", Rank: "S", CreatedAt: time.Now(), UpdatedAt: time.Now()},

	// --- Senjutsu ---
	{ID: 61, Name: "Sage Mode: Toad Sage Training", Description: sql.NullString{String: "Gathers natural energy from the environment to dramatically boost strength, speed, and jutsu power, learned through toad sage training.", Valid: true}, Type: "Senjutsu", Rank: "S", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 62, Name: "Frog Kata", Description: sql.NullString{String: "A senjutsu-enhanced taijutsu style that uses natural energy to sense and counter an opponent's attacks with minimal movement.", Valid: true}, Type: "Senjutsu", Rank: "A", CreatedAt: time.Now(), UpdatedAt: time.Now()},
	{ID: 63, Name: "Six Paths Sage Mode", Description: sql.NullString{String: "An extremely rare senjutsu form granting immense chakra reserves and abilities drawn directly from the Sage of Six Paths' power.", Valid: true}, Type: "Senjutsu", Rank: "S", CreatedAt: time.Now(), UpdatedAt: time.Now()},
}
