// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: characters_jutsus.sql

package sqlc

import (
	"context"
)

const createCharacterJutsu = `-- name: CreateCharacterJutsu :one
INSERT INTO characters_jutsus (character_id, jutsu_id)
VALUES (?, ?)
RETURNING id, character_id, jutsu_id, created_at
`

type CreateCharacterJutsuParams struct {
	CharacterID int64
	JutsuID     int64
}

func (q *Queries) CreateCharacterJutsu(ctx context.Context, arg CreateCharacterJutsuParams) (CharactersJutsu, error) {
	row := q.db.QueryRowContext(ctx, createCharacterJutsu, arg.CharacterID, arg.JutsuID)
	var i CharactersJutsu
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.JutsuID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCharacterJutsu = `-- name: DeleteCharacterJutsu :exec
DELETE FROM characters_jutsus
WHERE character_id = ? AND jutsu_id = ?
RETURNING id, character_id, jutsu_id, created_at
`

type DeleteCharacterJutsuParams struct {
	CharacterID int64
	JutsuID     int64
}

func (q *Queries) DeleteCharacterJutsu(ctx context.Context, arg DeleteCharacterJutsuParams) error {
	_, err := q.db.ExecContext(ctx, deleteCharacterJutsu, arg.CharacterID, arg.JutsuID)
	return err
}

const getCharactersByJutsuID = `-- name: GetCharactersByJutsuID :many
SELECT characters.id, characters.name, characters.nickname, characters.clan, characters.age, characters.rank, characters.birthdate, characters.village_id, characters.created_at, characters.updated_at
FROM characters
JOIN characters_jutsus ON characters_jutsus.character_id = characters.id
WHERE characters_jutsus.jutsu_id = ?
`

func (q *Queries) GetCharactersByJutsuID(ctx context.Context, jutsuID int64) ([]Character, error) {
	rows, err := q.db.QueryContext(ctx, getCharactersByJutsuID, jutsuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Nickname,
			&i.Clan,
			&i.Age,
			&i.Rank,
			&i.Birthdate,
			&i.VillageID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJutsusByCharacterID = `-- name: GetJutsusByCharacterID :many
SELECT jutsus.id, jutsus.name, jutsus.description, jutsus.type, jutsus.rank, jutsus.created_at, jutsus.updated_at
FROM jutsus
JOIN characters_jutsus ON characters_jutsus.jutsu_id = jutsus.id
WHERE characters_jutsus.character_id = ?
`

func (q *Queries) GetJutsusByCharacterID(ctx context.Context, characterID int64) ([]Jutsu, error) {
	rows, err := q.db.QueryContext(ctx, getJutsusByCharacterID, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Jutsu
	for rows.Next() {
		var i Jutsu
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Rank,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
