// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: characters.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO characters (name, nickname, clan, age, rank, birthdate, village_id)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, nickname, clan, age, rank, birthdate, village_id, created_at, updated_at, team_id
`

type CreateCharacterParams struct {
	Name      string
	Nickname  sql.NullString
	Clan      sql.NullString
	Age       sql.NullInt64
	Rank      string
	Birthdate time.Time
	VillageID int64
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, createCharacter,
		arg.Name,
		arg.Nickname,
		arg.Clan,
		arg.Age,
		arg.Rank,
		arg.Birthdate,
		arg.VillageID,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Nickname,
		&i.Clan,
		&i.Age,
		&i.Rank,
		&i.Birthdate,
		&i.VillageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}

const deleteCharacter = `-- name: DeleteCharacter :one
DELETE FROM characters WHERE id = ? RETURNING id, name, nickname, clan, age, rank, birthdate, village_id, created_at, updated_at, team_id
`

func (q *Queries) DeleteCharacter(ctx context.Context, id int64) (Character, error) {
	row := q.db.QueryRowContext(ctx, deleteCharacter, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Nickname,
		&i.Clan,
		&i.Age,
		&i.Rank,
		&i.Birthdate,
		&i.VillageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}

const getCharacter = `-- name: GetCharacter :one
SELECT id, name, nickname, clan, age, rank, birthdate, village_id, created_at, updated_at, team_id FROM characters WHERE id = ?
`

func (q *Queries) GetCharacter(ctx context.Context, id int64) (Character, error) {
	row := q.db.QueryRowContext(ctx, getCharacter, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Nickname,
		&i.Clan,
		&i.Age,
		&i.Rank,
		&i.Birthdate,
		&i.VillageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}

const getCharacters = `-- name: GetCharacters :many
SELECT id, name, nickname, clan, age, rank, birthdate, village_id, created_at, updated_at, team_id FROM characters
`

func (q *Queries) GetCharacters(ctx context.Context) ([]Character, error) {
	rows, err := q.db.QueryContext(ctx, getCharacters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Nickname,
			&i.Clan,
			&i.Age,
			&i.Rank,
			&i.Birthdate,
			&i.VillageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCharacter = `-- name: UpdateCharacter :one
UPDATE characters
SET
  name       = COALESCE(?1, name),
  nickname   = COALESCE(?2, nickname),
  clan       = COALESCE(?3, clan),
  age        = COALESCE(?4, age),
  rank       = COALESCE(?5, rank),
  birthdate  = COALESCE(?6, birthdate),
  village_id = COALESCE(?7, village_id),
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?8
RETURNING id, name, nickname, clan, age, rank, birthdate, village_id, created_at, updated_at, team_id
`

type UpdateCharacterParams struct {
	Name      sql.NullString
	Nickname  sql.NullString
	Clan      sql.NullString
	Age       sql.NullInt64
	Rank      sql.NullString
	Birthdate sql.NullTime
	VillageID sql.NullInt64
	ID        int64
}

func (q *Queries) UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, updateCharacter,
		arg.Name,
		arg.Nickname,
		arg.Clan,
		arg.Age,
		arg.Rank,
		arg.Birthdate,
		arg.VillageID,
		arg.ID,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Nickname,
		&i.Clan,
		&i.Age,
		&i.Rank,
		&i.Birthdate,
		&i.VillageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}
