// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jutsus.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createJutsu = `-- name: CreateJutsu :one
INSERT INTO jutsus (name, description, type, rank)
VALUES (?, ?, ?, ?)
RETURNING id, name, description, type, rank, created_at, updated_at
`

type CreateJutsuParams struct {
	Name        string
	Description sql.NullString
	Type        string
	Rank        string
}

func (q *Queries) CreateJutsu(ctx context.Context, arg CreateJutsuParams) (Jutsu, error) {
	row := q.db.QueryRowContext(ctx, createJutsu,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Rank,
	)
	var i Jutsu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Rank,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJutsu = `-- name: DeleteJutsu :one
DELETE FROM jutsus WHERE id = ? RETURNING id, name, description, type, rank, created_at, updated_at
`

func (q *Queries) DeleteJutsu(ctx context.Context, id int64) (Jutsu, error) {
	row := q.db.QueryRowContext(ctx, deleteJutsu, id)
	var i Jutsu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Rank,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJutsu = `-- name: GetJutsu :one
SELECT id, name, description, type, rank, created_at, updated_at FROM jutsus WHERE id = ?
`

func (q *Queries) GetJutsu(ctx context.Context, id int64) (Jutsu, error) {
	row := q.db.QueryRowContext(ctx, getJutsu, id)
	var i Jutsu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Rank,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJutsus = `-- name: GetJutsus :many
SELECT id, name, description, type, rank, created_at, updated_at FROM jutsus
`

func (q *Queries) GetJutsus(ctx context.Context) ([]Jutsu, error) {
	rows, err := q.db.QueryContext(ctx, getJutsus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Jutsu
	for rows.Next() {
		var i Jutsu
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Rank,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJutsu = `-- name: UpdateJutsu :one
UPDATE jutsus
SET
  name        = COALESCE(?1, name),
  description = COALESCE(?2, description),
  type        = COALESCE(?3, type),
  rank        = COALESCE(?4, rank),
  updated_at  = CURRENT_TIMESTAMP
WHERE id = ?5
RETURNING id, name, description, type, rank, created_at, updated_at
`

type UpdateJutsuParams struct {
	Name        sql.NullString
	Description sql.NullString
	Type        sql.NullString
	Rank        sql.NullString
	ID          int64
}

func (q *Queries) UpdateJutsu(ctx context.Context, arg UpdateJutsuParams) (Jutsu, error) {
	row := q.db.QueryRowContext(ctx, updateJutsu,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Rank,
		arg.ID,
	)
	var i Jutsu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Rank,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
