// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: missions.sql

package sqlc

import (
	"context"
	"time"
)

const createMission = `-- name: CreateMission :one
INSERT INTO missions (name, description, assigned_to, rank, status, reward, starts_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, description, assigned_to, rank, status, reward, starts_at, created_at, updated_at
`

type CreateMissionParams struct {
	Name        string
	Description string
	AssignedTo  int64
	Rank        string
	Status      string
	Reward      int64
	StartsAt    time.Time
}

func (q *Queries) CreateMission(ctx context.Context, arg CreateMissionParams) (Mission, error) {
	row := q.db.QueryRowContext(ctx, createMission,
		arg.Name,
		arg.Description,
		arg.AssignedTo,
		arg.Rank,
		arg.Status,
		arg.Reward,
		arg.StartsAt,
	)
	var i Mission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AssignedTo,
		&i.Rank,
		&i.Status,
		&i.Reward,
		&i.StartsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMission = `-- name: DeleteMission :one
DELETE FROM missions
WHERE id = ?
RETURNING id, name, description, assigned_to, rank, status, reward, starts_at, created_at, updated_at
`

func (q *Queries) DeleteMission(ctx context.Context, id int64) (Mission, error) {
	row := q.db.QueryRowContext(ctx, deleteMission, id)
	var i Mission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AssignedTo,
		&i.Rank,
		&i.Status,
		&i.Reward,
		&i.StartsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMission = `-- name: GetMission :one
SELECT id, name, description, assigned_to, rank, status, reward, starts_at, created_at, updated_at FROM missions
WHERE id = ?
`

func (q *Queries) GetMission(ctx context.Context, id int64) (Mission, error) {
	row := q.db.QueryRowContext(ctx, getMission, id)
	var i Mission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AssignedTo,
		&i.Rank,
		&i.Status,
		&i.Reward,
		&i.StartsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMissionsByTeam = `-- name: GetMissionsByTeam :many
SELECT id, name, description, assigned_to, rank, status, reward, starts_at, created_at, updated_at FROM missions
WHERE assigned_to = ?
`

func (q *Queries) GetMissionsByTeam(ctx context.Context, assignedTo int64) ([]Mission, error) {
	rows, err := q.db.QueryContext(ctx, getMissionsByTeam, assignedTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mission
	for rows.Next() {
		var i Mission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AssignedTo,
			&i.Rank,
			&i.Status,
			&i.Reward,
			&i.StartsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMissions = `-- name: ListMissions :many
SELECT id, name, description, assigned_to, rank, status, reward, starts_at, created_at, updated_at FROM missions
`

func (q *Queries) ListMissions(ctx context.Context) ([]Mission, error) {
	rows, err := q.db.QueryContext(ctx, listMissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mission
	for rows.Next() {
		var i Mission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AssignedTo,
			&i.Rank,
			&i.Status,
			&i.Reward,
			&i.StartsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
