// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type Character struct {
	ID        int64
	Name      string
	Nickname  sql.NullString
	Clan      sql.NullString
	Age       sql.NullInt64
	Rank      string
	Birthdate time.Time
	VillageID int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Jutsu struct {
	ID          int64
	Name        string
	Description sql.NullString
	Type        string
	Rank        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Village struct {
	ID          int64
	Name        string
	Description sql.NullString
	Land        string
	Population  sql.NullInt64
	KageID      sql.NullInt64
	FoundedAt   time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
