// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type User struct {
	ID        int64
	Username  string
	FullName  string
	Email     string
	CreatedAt time.Time
}
