// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type Village struct {
	ID          int64
	Name        string
	Description sql.NullString
	Land        string
	Population  sql.NullInt64
	KageID      sql.NullInt64
	FoundedAt   time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
