// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_members.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const addTeamMember = `-- name: AddTeamMember :one
INSERT INTO team_members (team_id, character_id, role)
VALUES (?, ?, ?)
RETURNING team_id, character_id, role, joined_at
`

type AddTeamMemberParams struct {
	TeamID      int64
	CharacterID int64
	Role        string
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRowContext(ctx, addTeamMember, arg.TeamID, arg.CharacterID, arg.Role)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.CharacterID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const characterIsSenseiOfAnyTeam = `-- name: CharacterIsSenseiOfAnyTeam :one
SELECT COUNT(*) FROM team_members WHERE character_id = ? AND role = 'Sensei'
`

func (q *Queries) CharacterIsSenseiOfAnyTeam(ctx context.Context, characterID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, characterIsSenseiOfAnyTeam, characterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCharacterMembership = `-- name: GetCharacterMembership :one
SELECT team_id, character_id, role, joined_at FROM team_members
WHERE character_id = ?
`

func (q *Queries) GetCharacterMembership(ctx context.Context, characterID int64) (TeamMember, error) {
	row := q.db.QueryRowContext(ctx, getCharacterMembership, characterID)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.CharacterID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getTeamDetails = `-- name: GetTeamDetails :many
SELECT
    t.id AS team_id,
    t.name AS team_name,
    t.created_at AS team_created_at,
    c.id, c.name, c.nickname, c.clan, c.age, c.rank, c.birthdate, c.village_id, c.created_at, c.updated_at,
    tm.role,
    tm.joined_at
FROM teams t
LEFT JOIN team_members tm ON tm.team_id = t.id
LEFT JOIN characters c ON c.id = tm.character_id
WHERE t.id = ?
`

type GetTeamDetailsRow struct {
	TeamID        int64
	TeamName      string
	TeamCreatedAt time.Time
	ID            sql.NullInt64
	Name          sql.NullString
	Nickname      sql.NullString
	Clan          sql.NullString
	Age           sql.NullInt64
	Rank          sql.NullString
	Birthdate     sql.NullTime
	VillageID     sql.NullInt64
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	Role          sql.NullString
	JoinedAt      sql.NullTime
}

func (q *Queries) GetTeamDetails(ctx context.Context, id int64) ([]GetTeamDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTeamDetails, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamDetailsRow
	for rows.Next() {
		var i GetTeamDetailsRow
		if err := rows.Scan(
			&i.TeamID,
			&i.TeamName,
			&i.TeamCreatedAt,
			&i.ID,
			&i.Name,
			&i.Nickname,
			&i.Clan,
			&i.Age,
			&i.Rank,
			&i.Birthdate,
			&i.VillageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamSensei = `-- name: GetTeamSensei :one
SELECT team_id, character_id, role, joined_at FROM team_members
WHERE team_id = ? AND role = 'Sensei'
`

func (q *Queries) GetTeamSensei(ctx context.Context, teamID int64) (TeamMember, error) {
	row := q.db.QueryRowContext(ctx, getTeamSensei, teamID)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.CharacterID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const removeTeamMember = `-- name: RemoveTeamMember :one
DELETE FROM team_members
WHERE team_id = ? AND character_id = ?
RETURNING team_id, character_id, role, joined_at
`

type RemoveTeamMemberParams struct {
	TeamID      int64
	CharacterID int64
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRowContext(ctx, removeTeamMember, arg.TeamID, arg.CharacterID)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.CharacterID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}
