// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package sqlc

import (
	"context"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name)
VALUES (?)
RETURNING id, name, created_at
`

func (q *Queries) CreateTeam(ctx context.Context, name string) (Team, error) {
	row := q.db.QueryRowContext(ctx, createTeam, name)
	var i Team
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :one
DELETE FROM teams
WHERE id = ?
RETURNING id, name, created_at
`

func (q *Queries) DeleteTeam(ctx context.Context, id int64) (Team, error) {
	row := q.db.QueryRowContext(ctx, deleteTeam, id)
	var i Team
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTeam = `-- name: GetTeam :one
SELECT id, name, created_at FROM teams
WHERE id = ?
`

func (q *Queries) GetTeam(ctx context.Context, id int64) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeam, id)
	var i Team
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listTeams = `-- name: ListTeams :many
SELECT id, name, created_at FROM teams
ORDER BY id
`

func (q *Queries) ListTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams
SET name = ?
WHERE id = ?
RETURNING id, name, created_at
`

type UpdateTeamParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, updateTeam, arg.Name, arg.ID)
	var i Team
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
