// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: villages.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createVillage = `-- name: CreateVillage :one
INSERT INTO villages (name,description,land,population,kage_id,founded_at)
VALUES (?,?,?,?,?,?) 
RETURNING id, name, description, land, population, kage_id, founded_at, created_at, updated_at
`

type CreateVillageParams struct {
	Name        string
	Description sql.NullString
	Land        string
	Population  sql.NullInt64
	KageID      sql.NullInt64
	FoundedAt   time.Time
}

func (q *Queries) CreateVillage(ctx context.Context, arg CreateVillageParams) (Village, error) {
	row := q.db.QueryRowContext(ctx, createVillage,
		arg.Name,
		arg.Description,
		arg.Land,
		arg.Population,
		arg.KageID,
		arg.FoundedAt,
	)
	var i Village
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Land,
		&i.Population,
		&i.KageID,
		&i.FoundedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVillage = `-- name: DeleteVillage :one
DELETE FROM villages WHERE id=? RETURNING id, name, description, land, population, kage_id, founded_at, created_at, updated_at
`

func (q *Queries) DeleteVillage(ctx context.Context, id int64) (Village, error) {
	row := q.db.QueryRowContext(ctx, deleteVillage, id)
	var i Village
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Land,
		&i.Population,
		&i.KageID,
		&i.FoundedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVillage = `-- name: GetVillage :one
SELECT id, name, description, land, population, kage_id, founded_at, created_at, updated_at FROM villages WHERE id=?
`

func (q *Queries) GetVillage(ctx context.Context, id int64) (Village, error) {
	row := q.db.QueryRowContext(ctx, getVillage, id)
	var i Village
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Land,
		&i.Population,
		&i.KageID,
		&i.FoundedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVillages = `-- name: GetVillages :many
SELECT id, name, description, land, population, kage_id, founded_at, created_at, updated_at FROM villages
`

func (q *Queries) GetVillages(ctx context.Context) ([]Village, error) {
	rows, err := q.db.QueryContext(ctx, getVillages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Village
	for rows.Next() {
		var i Village
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Land,
			&i.Population,
			&i.KageID,
			&i.FoundedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVillage = `-- name: UpdateVillage :one
UPDATE villages
SET
  name        = COALESCE(?1, name),
  description = COALESCE(?2, description),
  land        = COALESCE(?3, land),
  population  = COALESCE(?4, population),
  kage_id     = COALESCE(?5, kage_id),
  founded_at  = COALESCE(?6, founded_at),
  updated_at  = CURRENT_TIMESTAMP
WHERE id = ?7
RETURNING id, name, description, land, population, kage_id, founded_at, created_at, updated_at
`

type UpdateVillageParams struct {
	Name        sql.NullString
	Description sql.NullString
	Land        sql.NullString
	Population  sql.NullInt64
	KageID      sql.NullInt64
	FoundedAt   sql.NullTime
	ID          int64
}

func (q *Queries) UpdateVillage(ctx context.Context, arg UpdateVillageParams) (Village, error) {
	row := q.db.QueryRowContext(ctx, updateVillage,
		arg.Name,
		arg.Description,
		arg.Land,
		arg.Population,
		arg.KageID,
		arg.FoundedAt,
		arg.ID,
	)
	var i Village
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Land,
		&i.Population,
		&i.KageID,
		&i.FoundedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
