package store

import "github.com/biplob-codes/mockly/internal/model"

var Users = []model.User{
	{Id: 1, Name: "Sasuke Uchiha", Username: "sasukeuchiha", Email: "sasuke@uchiha.konoha", Phone: "555-0116", Website: "sasukeuchiha.konoha", Avatar: "https://res.cloudinary.com/dghw9vqu0/image/upload/w_64,h_64,c_fill,g_face/v1779978782/Sasuke_Part_1_cvfxqy.webp",
		Address: model.Address{Street: "Uchiha Clan Compound", City: "Konohagakure", State: "Land of Fire", ZipCode: "00007", Country: "Naruto World"},
		Company: model.Company{Name: "Uchiha Clan", CatchPhrase: "Avenge, then transcend", Industry: "Shinobi"}, CreatedAt: "2023-03-01T09:00:00Z"},
	{Id: 2, Name: "Kakashi Hatake", Username: "kakashihatake", Email: "kakashi@hatake.konoha", Phone: "555-0117", Website: "kakashihatake.konoha", Avatar: "https://res.cloudinary.com/dghw9vqu0/image/upload/w_64,h_64,c_fill,g_face/v1779978041/1000_k8et4f.webp",
		Address: model.Address{Street: "Team 7 Training Grounds", City: "Konohagakure", State: "Land of Fire", ZipCode: "00006", Country: "Naruto World"},
		Company: model.Company{Name: "Konoha Hokage Office", CatchPhrase: "Those who abandon the mission are trash", Industry: "Shinobi"}, CreatedAt: "2023-03-02T09:10:00Z"},
	{Id: 3, Name: "Itachi Uchiha", Username: "itachiuchiha", Email: "itachi@uchiha.konoha", Phone: "555-0118", Website: "itachiuchiha.konoha", Avatar: "https://res.cloudinary.com/dghw9vqu0/image/upload/w_64,h_64,c_fill,g_face/v1779978781/Itachi_iaie7p.webp",
		Address: model.Address{Street: "Uchiha Clan Compound", City: "Konohagakure", State: "Land of Fire", ZipCode: "00007", Country: "Naruto World"},
		Company: model.Company{Name: "Akatsuki", CatchPhrase: "Sacrifice for peace", Industry: "Espionage"}, CreatedAt: "2023-03-03T09:20:00Z"},
	{Id: 4, Name: "Tobirama Senju", Username: "tobiramasenju", Email: "tobirama@senju.konoha", Phone: "555-0119", Website: "tobiramasenju.konoha", Avatar: "https://res.cloudinary.com/dghw9vqu0/image/upload/w_64,h_64,c_fill,g_face/v1779978783/Tobirama_Senju_tmbjti.webp",
		Address: model.Address{Street: "Senju Clan Estate", City: "Konohagakure", State: "Land of Fire", ZipCode: "00002", Country: "Naruto World"},
		Company: model.Company{Name: "Second Hokage's Office", CatchPhrase: "Founder of shinobi systems", Industry: "Shinobi"}, CreatedAt: "2023-03-04T09:30:00Z"},
	{Id: 5, Name: "Minato Namikaze", Username: "minatonamikaze", Email: "minato@namikaze.konoha", Phone: "555-0120", Website: "minatonamikaze.konoha", Avatar: "https://res.cloudinary.com/dghw9vqu0/image/upload/w_64,h_64,c_fill,g_face/v1779978781/Minato_Namikaze_praaaj.webp",
		Address: model.Address{Street: "Hokage Residence", City: "Konohagakure", State: "Land of Fire", ZipCode: "00004", Country: "Naruto World"},
		Company: model.Company{Name: "Fourth Hokage's Office", CatchPhrase: "The Yellow Flash never stops", Industry: "Shinobi"}, CreatedAt: "2023-03-05T09:40:00Z"},
	{Id: 6, Name: "Jiraiya Sensei", Username: "jiraiyasensei", Email: "jiraiya@sannin.konoha", Phone: "555-0121", Website: "jiraiyasensei.konoha", Avatar: "https://res.cloudinary.com/dghw9vqu0/image/upload/w_64,h_64,c_fill,g_face/v1779978782/Profile_Jiraiya.PNG_hs7r5p.webp",
		Address: model.Address{Street: "Mount Myoboku", City: "Konohagakure", State: "Land of Fire", ZipCode: "00099", Country: "Naruto World"},
		Company: model.Company{Name: "Legendary Sannin", CatchPhrase: "Research makes the world go round", Industry: "Publishing & Shinobi"}, CreatedAt: "2023-03-06T09:50:00Z"},
	{Id: 7, Name: "Tsunade Senju", Username: "tsunadesenju", Email: "tsunade@senju.konoha", Phone: "555-0122", Website: "tsunadesenju.konoha", Avatar: "https://res.cloudinary.com/dghw9vqu0/image/upload/w_64,h_64,c_fill,g_face/v1779978783/Tsunade_infobox2_jgqswd.webp",
		Address: model.Address{Street: "Hokage Tower", City: "Konohagakure", State: "Land of Fire", ZipCode: "00005", Country: "Naruto World"},
		Company: model.Company{Name: "Fifth Hokage's Office", CatchPhrase: "Never go back on your word", Industry: "Medical & Shinobi"}, CreatedAt: "2023-03-07T10:00:00Z"},
	{Id: 8, Name: "Shikamaru Nara", Username: "shikamarunara", Email: "shikamaru@nara.konoha", Phone: "555-0123", Website: "shikamarunara.konoha", Avatar: "https://res.cloudinary.com/dghw9vqu0/image/upload/w_64,h_64,c_fill,g_face/v1779978783/Shikamaru_Nara_efaqim.webp",
		Address: model.Address{Street: "Nara Clan Forest", City: "Konohagakure", State: "Land of Fire", ZipCode: "00012", Country: "Naruto World"},
		Company: model.Company{Name: "Nara Clan Strategy Corps", CatchPhrase: "What a drag, but fine", Industry: "Strategy & Shinobi"}, CreatedAt: "2023-03-08T10:10:00Z"},
	{Id: 9, Name: "Gaara Kazekage", Username: "gaarakazekage", Email: "gaara@kazekage.konoha", Phone: "555-0124", Website: "gaarakazekage.suna", Avatar: "https://res.cloudinary.com/dghw9vqu0/image/upload/w_64,h_64,c_fill,g_face/v1779979216/1000_vxeuwh.webp",
		Address: model.Address{Street: "Kazekage Tower", City: "Sunagakure", State: "Land of Wind", ZipCode: "00001", Country: "Naruto World"},
		Company: model.Company{Name: "Fifth Kazekage's Office", CatchPhrase: "Love is my shield", Industry: "Shinobi"}, CreatedAt: "2023-03-09T10:20:00Z"},
	{Id: 10, Name: "Madara Uchiha", Username: "madarauchiha", Email: "madara@uchiha.konoha", Phone: "555-0125", Website: "madarauchiha.konoha", Avatar: "https://res.cloudinary.com/dghw9vqu0/image/upload/w_64,h_64,c_fill,g_face/v1779978781/Madara_img2_y2hsfd.webp",
		Address: model.Address{Street: "Valley of the End", City: "Konohagakure", State: "Land of Fire", ZipCode: "00013", Country: "Naruto World"},
		Company: model.Company{Name: "Uchiha Clan", CatchPhrase: "I am the ghost of the Uchiha", Industry: "Shinobi"}, CreatedAt: "2023-03-10T10:30:00Z"},
	{Id: 11, Name: "Hinata Hyuga", Username: "hinatahyuga", Email: "hinata@hyuga.konoha", Phone: "555-0126", Website: "hinatahyuga.konoha", Avatar: "https://res.cloudinary.com/dghw9vqu0/image/upload/w_64,h_64,c_fill,g_face/v1779978781/Hinata_27s_byakugan_a71wen.webp",
		Address: model.Address{Street: "Hyuga Clan Compound", City: "Konohagakure", State: "Land of Fire", ZipCode: "00008", Country: "Naruto World"},
		Company: model.Company{Name: "Hyuga Clan", CatchPhrase: "Gentle fist, strong heart", Industry: "Shinobi"}, CreatedAt: "2023-03-11T10:40:00Z"},
	{Id: 12, Name: "Neji Hyuga", Username: "nejihyuga", Email: "neji@hyuga.konoha", Phone: "555-0127", Website: "nejihyuga.konoha", Avatar: "https://res.cloudinary.com/dghw9vqu0/image/upload/w_64,h_64,c_fill,g_face/v1779978782/Neji_Part_I_Screenshot_jsg7gw.webp",
		Address: model.Address{Street: "Hyuga Branch House", City: "Konohagakure", State: "Land of Fire", ZipCode: "00009", Country: "Naruto World"},
		Company: model.Company{Name: "Hyuga Clan", CatchPhrase: "Fate is not absolute", Industry: "Shinobi"}, CreatedAt: "2023-03-12T10:50:00Z"},
	{Id: 13, Name: "Hashirama Senju", Username: "hashiramasenju", Email: "hashirama@senju.konoha", Phone: "555-0128", Website: "hashiramasenju.konoha", Avatar: "https://res.cloudinary.com/dghw9vqu0/image/upload/w_64,h_64,c_fill,g_face/v1779978780/Hashirama_Senju_exdjcg.webp",
		Address: model.Address{Street: "Hokage Monument", City: "Konohagakure", State: "Land of Fire", ZipCode: "00003", Country: "Naruto World"},
		Company: model.Company{Name: "First Hokage's Office", CatchPhrase: "Founder of Konohagakure", Industry: "Shinobi"}, CreatedAt: "2023-03-13T11:00:00Z"},
	{Id: 14, Name: "Obito Uchiha", Username: "obitouchiha", Email: "obito@uchiha.konoha", Phone: "555-0129", Website: "obitouchiha.konoha", Avatar: "https://res.cloudinary.com/dghw9vqu0/image/upload/w_64,h_64,c_fill,g_face/v1779978782/Obito_Uchiha_sti38x.webp",
		Address: model.Address{Street: "Kamui Dimension", City: "Konohagakure", State: "Land of Fire", ZipCode: "00014", Country: "Naruto World"},
		Company: model.Company{Name: "Akatsuki", CatchPhrase: "Those who break the rules are scum", Industry: "Espionage"}, CreatedAt: "2023-03-14T11:10:00Z"},
}
