package store

import "github.com/biplob-codes/mockly/internal/model"

var Users = []model.User{
	{Id: 1, Name: "Tom Cruise", Username: "tomcruise", Email: "tom@example.com", Phone: "555-0101", Website: "tomcruise.com", Avatar: "https://i.pravatar.cc/150?img=1",
		Address: model.Address{Street: "123 Sunset Blvd", City: "Los Angeles", State: "CA", ZipCode: "90028", Country: "USA"},
		Company: model.Company{Name: "Cruise Films", CatchPhrase: "Mission accepted", Industry: "Entertainment"}, CreatedAt: "2023-01-10T09:00:00Z"},
	{Id: 2, Name: "Robert Downey Jr", Username: "rdj", Email: "robert@example.com", Phone: "555-0102", Website: "rdj.com", Avatar: "https://i.pravatar.cc/150?img=2",
		Address: model.Address{Street: "456 Stark Ave", City: "New York", State: "NY", ZipCode: "10001", Country: "USA"},
		Company: model.Company{Name: "Stark Industries", CatchPhrase: "Genius, billionaire, playboy", Industry: "Technology"}, CreatedAt: "2023-01-12T10:15:00Z"},
	{Id: 3, Name: "Benedict Cumberbatch", Username: "bcumberbatch", Email: "benedict@example.com", Phone: "555-0103", Website: "benedictc.com", Avatar: "https://i.pravatar.cc/150?img=3",
		Address: model.Address{Street: "12 Baker Street", City: "London", State: "England", ZipCode: "NW1", Country: "UK"},
		Company: model.Company{Name: "Sanctum Sanctorum", CatchPhrase: "Master of the mystic arts", Industry: "Entertainment"}, CreatedAt: "2023-01-15T08:30:00Z"},
	{Id: 4, Name: "Brad Pitt", Username: "bradpitt", Email: "brad@example.com", Phone: "555-0104", Website: "bradpitt.com", Avatar: "https://i.pravatar.cc/150?img=4",
		Address: model.Address{Street: "78 Malibu Rd", City: "Malibu", State: "CA", ZipCode: "90265", Country: "USA"},
		Company: model.Company{Name: "Plan B Entertainment", CatchPhrase: "Produce boldly", Industry: "Entertainment"}, CreatedAt: "2023-01-18T11:45:00Z"},
	{Id: 5, Name: "Scarlett Johansson", Username: "scarjo", Email: "scarlett@example.com", Phone: "555-0105", Website: "scarjo.com", Avatar: "https://i.pravatar.cc/150?img=5",
		Address: model.Address{Street: "22 Broadway", City: "New York", State: "NY", ZipCode: "10004", Country: "USA"},
		Company: model.Company{Name: "SJ Studios", CatchPhrase: "Black widow bites back", Industry: "Entertainment"}, CreatedAt: "2023-01-20T09:20:00Z"},
	{Id: 6, Name: "Priyanka Chopra", Username: "priyankachopra", Email: "priyanka@example.com", Phone: "555-0106", Website: "priyankac.com", Avatar: "https://i.pravatar.cc/150?img=6",
		Address: model.Address{Street: "9 Marine Drive", City: "Mumbai", State: "Maharashtra", ZipCode: "400002", Country: "India"},
		Company: model.Company{Name: "Purple Pebble Pictures", CatchPhrase: "Stories that matter", Industry: "Entertainment"}, CreatedAt: "2023-01-22T07:10:00Z"},
	{Id: 7, Name: "Shah Rukh Khan", Username: "iamsrk", Email: "srk@example.com", Phone: "555-0107", Website: "shahrukhkhan.com", Avatar: "https://i.pravatar.cc/150?img=7",
		Address: model.Address{Street: "Mannat, Bandstand", City: "Mumbai", State: "Maharashtra", ZipCode: "400050", Country: "India"},
		Company: model.Company{Name: "Red Chillies Entertainment", CatchPhrase: "King of romance", Industry: "Entertainment"}, CreatedAt: "2023-01-25T06:40:00Z"},
	{Id: 8, Name: "Emma Watson", Username: "emmawatson", Email: "emma@example.com", Phone: "555-0108", Website: "emmawatson.com", Avatar: "https://i.pravatar.cc/150?img=8",
		Address: model.Address{Street: "5 Oxford Street", City: "London", State: "England", ZipCode: "W1D", Country: "UK"},
		Company: model.Company{Name: "Watson Foundation", CatchPhrase: "Read, learn, act", Industry: "Non-profit"}, CreatedAt: "2023-02-01T12:00:00Z"},
	{Id: 9, Name: "Keanu Reeves", Username: "keanureeves", Email: "keanu@example.com", Phone: "555-0109", Website: "keanureeves.com", Avatar: "https://i.pravatar.cc/150?img=9",
		Address: model.Address{Street: "88 Yonge St", City: "Toronto", State: "Ontario", ZipCode: "M5C", Country: "Canada"},
		Company: model.Company{Name: "Arch Motorcycle", CatchPhrase: "Breathtaking", Industry: "Manufacturing"}, CreatedAt: "2023-02-04T15:25:00Z"},
	{Id: 10, Name: "Zendaya", Username: "zendaya", Email: "zendaya@example.com", Phone: "555-0110", Website: "zendaya.com", Avatar: "https://i.pravatar.cc/150?img=10",
		Address: model.Address{Street: "300 Vine St", City: "Oakland", State: "CA", ZipCode: "94607", Country: "USA"},
		Company: model.Company{Name: "Bold Media", CatchPhrase: "Own your story", Industry: "Entertainment"}, CreatedAt: "2023-02-06T13:55:00Z"},
	{Id: 11, Name: "Ryan Reynolds", Username: "ryanreynolds", Email: "ryan@example.com", Phone: "555-0111", Website: "ryanreynolds.com", Avatar: "https://i.pravatar.cc/150?img=11",
		Address: model.Address{Street: "77 Bank St", City: "Vancouver", State: "BC", ZipCode: "V6C", Country: "Canada"},
		Company: model.Company{Name: "Maximum Effort", CatchPhrase: "Marketing with a wink", Industry: "Media"}, CreatedAt: "2023-02-09T10:05:00Z"},
	{Id: 12, Name: "Deepika Padukone", Username: "deepikap", Email: "deepika@example.com", Phone: "555-0112", Website: "deepikap.com", Avatar: "https://i.pravatar.cc/150?img=12",
		Address: model.Address{Street: "14 MG Road", City: "Bangalore", State: "Karnataka", ZipCode: "560001", Country: "India"},
		Company: model.Company{Name: "Ka Productions", CatchPhrase: "Bold and beautiful", Industry: "Entertainment"}, CreatedAt: "2023-02-11T08:15:00Z"},
	{Id: 13, Name: "Tom Holland", Username: "tomholland", Email: "tomholland@example.com", Phone: "555-0113", Website: "tomholland.com", Avatar: "https://i.pravatar.cc/150?img=13",
		Address: model.Address{Street: "42 Kingston Rd", City: "Kingston upon Thames", State: "England", ZipCode: "KT1", Country: "UK"},
		Company: model.Company{Name: "Holland Productions", CatchPhrase: "Friendly neighborhood", Industry: "Entertainment"}, CreatedAt: "2023-02-14T09:45:00Z"},
	{Id: 14, Name: "Ana de Armas", Username: "anadearmas", Email: "ana@example.com", Phone: "555-0114", Website: "anadearmas.com", Avatar: "https://i.pravatar.cc/150?img=14",
		Address: model.Address{Street: "18 Vedado", City: "Havana", State: "Havana", ZipCode: "10400", Country: "Cuba"},
		Company: model.Company{Name: "de Armas Films", CatchPhrase: "Passion on screen", Industry: "Entertainment"}, CreatedAt: "2023-02-17T11:35:00Z"},
	{Id: 15, Name: "Idris Elba", Username: "idriselba", Email: "idris@example.com", Phone: "555-0115", Website: "idriselba.com", Avatar: "https://i.pravatar.cc/150?img=15",
		Address: model.Address{Street: "5 Hackney Rd", City: "London", State: "England", ZipCode: "E2", Country: "UK"},
		Company: model.Company{Name: "Green Door Pictures", CatchPhrase: "Versatile and unstoppable", Industry: "Entertainment"}, CreatedAt: "2023-02-20T14:00:00Z"},
}